### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by R4356th**
### Changes

Sets up Travis CI and adds Travis CI badge.

### Status 

Work in Progress

### CODE REVIEW

**Comment by R4356th** [comment]
@GrahamSH-LLK, I need you to prepare the .travis.yml file. I have left some notes in the file which could help you.

**Comment by R4356th** [comment]
Please ping me after it is ready.

**Comment by GrahamSH-LLK** [comment]
@R4356th Done!

**Review by R4356th — COMMENTED** [review]
The build is failing. Please check the Checks tab.

**Pull request merged**
