### PR TITLE
My changes

### PR DESCRIPTION
**Pull request by R4356th**
What do we have to do with BJC? Why is there a gitignore file when there is nothing to ignore? Why do we need a README consisting of just two words inside a directory? Why are B Romagosa (bromagosa) and M Ball (cycomachead) not credited?

### CODE REVIEW

**Review by GrahamSH-LLK — APPROVED** [review]
Looks good.

**Comment by R4356th** [comment]
I will merge this after Travis CI is set up.

**Comment by GrahamSH-LLK** [comment]
Sure!

**Comment by R4356th** [comment]
@GrahamSH-LLK, a .gitignore file tells Git what not to track. The functionality in this case is not tracking all files with the .save file extension. There is no file with that extension so that file can be safely deleted.

**Comment by R4356th** [comment]
I will reopen this for Travis to start the build now.

**Comment by R4356th** [comment]
All necessary builds have passed. I am merging this. 🆗

**Pull request merged**
